### ISSUE TITLE
Docker Hub Image

### ISSUE THREAD

**Issue by meichthys** [metikular/coupon-store#1]
The example docker compose doesn't seem to work. Is the image available on docker hub? I can't seem to find it.

**Comment by meichthys** [comment]
That will probably work if i clone the repo and run from the local directory. 
Generally I deploy from portainer which doesn't clone the repo, but rather relies on the hosted version of images (either dockerhub or github).

**Comment by phylor** [comment]
There is now an image on DockerHub: https://hub.docker.com/r/metikular/coupon-store

The problem with building the docker image locally should also be fixed now!
