### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by meichthys** [metikular/coupon-store#13]
How does this application persist storage? Normally a doctor image has a volume parameter that specifies where the data should be stored. If there is a database container included like this one then the database files would be in the volume storage.

**Comment by mariushosting** [comment]
+1

**Comment by phylor** [comment]
The data is stored in a linked PostgreSQL container. The docker image on DockerHub of the application currently doesn't store any data.

I added a volume to the example `docker-compose.yml` to illustrate how to setup a volume for PostgreSQL (cf. 1cb064cdfc54a42062eb0c51f6bb24007fffe3a4).

You shouldn't rely on that volume for backups though. It's better to dump the database using `pg_dump` regularly.

Let me know if there are any other questions!
