### ISSUE TITLE
Add version number to footer

### ISSUE THREAD

**Issue by meichthys** [metikular/coupon-store#19]
It would be nice to be able to see the coupon-store version number in the frontend (maybe on the right part of the footer?) something like:
![image](https://user-images.githubusercontent.com/10717998/193392283-310ef730-dcbd-47e0-a267-3432f645e93d.png)

**Comment by phylor** [comment]
Good idea! Maybe the footer is a bit too prominent, but we could put it on the account page.

**Comment by meichthys** [comment]
Yeah that sounds like a good spot for it 👍

**Comment by phylor** [comment]
Implemented in 0d7bc71f081e30a4f7a98e457a2d70ac78762a3e
