### ISSUE TITLE
self hosted installation script

### ISSUE THREAD

**Issue by aspx1981** [metikular/coupon-store#259]
hello,
I tried the online version and I'd like to install on my ubuntu but without docker,
I'm trying to create the DB schema and install the code to use with ngnix, but no luck,
do you have some hints ? because I don't know ruby.

thanks a lot

**Comment by phylor** [comment]
This is a bit more elaborate. What you need:

- Ruby 3.2.2. Not sure what Ubuntu has at the moment, you might need to use rbenv to install the correct Ruby version. Although it's not a hard dependency, so you might get lucky and be able to run it with an older version.
- A database or use sqlite: `DATABASE_URL=sqlite3:db/data/coupons.sqlite3`
- Ensure you have the following environment variables set:

```
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE=set-to-some-random-string
CODE_VERSION=latest
```
- In the application directory, run the following to install dependencies:

```shell
bundle config set --local without 'development test'
bundle install
```

- To setup assets:

```shell
bin/rails assets:precompile
```

- Setup database. Either set `DATABASE_URL` accordingly, or change settings in `config/database.yml`.

```shell
bin/rails db:create db:migrate
```

- Start the server. You could then proxy with nginx to port `1818`.

```shell
bin/rails server -b 127.0.0.1 --port=1818
```

If that doesn't work, let me know what errors you get!

**Comment by phylor** [comment]
Closing as no feedback in a while. Let me know if you need more help - otherwise looking at the Dockerfile should get an impression on how to self-install.
