### ISSUE TITLE
Feature Request // Expiry Notifications

### ISSUE THREAD

**Issue by l4rm4nd** [metikular/coupon-store#327]
Thanks for this cool project!

It would be cool if vouchers that will soon expire trigger a notification (e.g. via e-mail).

The user shall able to define how many days beforehand he would like to be reminded.

For such notifications one may use [apprise](https://github.com/caronc/apprise). Quite a comfortable way of supporting various notification channels programmatically via one function call.

**Comment by l4rm4nd** [comment]
Also a full-text search would be great

**Comment by phylor** [comment]
Thank you @l4rm4nd for the issue! Search is now implemented. Notifications are a good idea, will add those!

**Comment by phylor** [comment]
Implemented in https://github.com/metikular/coupon-store/releases/tag/v2.0.0
