### ISSUE TITLE
[ARM] Unable to start / deploy the container

### ISSUE THREAD

**Issue by Kimbaras** [metikular/coupon-store#81]
Hi,

I've tried to deploy using docker compose (both SQLite and PostgreSQL versions) but seems the container is not starting correctly.

For both versions, the container starts but in the logs I receive the following error
![error](https://user-images.githubusercontent.com/102742484/214912262-57a6de15-8be5-4fc6-9e1a-ff9d866c8aa3.png)

I'm trying on an **arm64** Ubuntu 20.04 distro, could it be related?
I've not yet tried on an amd64 (the standard 64bit distro) but if that is the case I think it should be mentioned (as this would basically exclude any deployments on Raspberry or other arm systems).

Also, but maybe this is just because I haven't yet got it to work, on which port should it respond? 
The standard http (80)? Some custom port?

Thanks!

**Comment by phylor** [comment]
@Kimbaras ARM should eventually be supported (again). It currently fails because of some dependencies. I'll try on the weekend if I can get it running on a Raspberry.

You could try it yourself by building the docker image, but I doubt that it works without changes.

> Also, but maybe this is just because I haven't yet got it to work, on which port should it respond?
The standard http (80)? Some custom port?

Yes, it's port `80`. I added a note to the `README`.

**Comment by Kimbaras** [comment]
Got, thanks for the info!

I'll try to deploy on a regular amd64 VMs to start playing with it, but in the end I'd like to run on the Pi / on arm.

> Yes, it's port 80. I added a note to the README.

Again, thanks for the heads-up!

**Comment by phylor** [comment]
[Release 1.3.0](https://github.com/metikular/coupon-store/releases/tag/v1.3.0) works for me on the Raspberry Pi 3. You can just pull the docker image again using `docker pull metikular/coupon-store`, or `docker-compose pull`. Let me know if there are still any issues!
