### ISSUE TITLE
More barcode types?

### ISSUE THREAD

**Issue by Yhprum** [metikular/coupon-store#90]
My loyalty cards aren't supported by this - I have a couple 12 digit UPC codes and a PDF417 code I don't know the number to (but could maybe find using a separate barcode scanner.

Would there be a way to support these kinds of barcodes, or have pictures of barcodes that aren't supported so I'd be able to add all my cards?

**Comment by phylor** [comment]
> My loyalty cards aren't supported by this - I have a couple 12 digit UPC codes and a PDF417 code I don't know the number to (but could maybe find using a separate barcode scanner.

* For the 12 digit UPC codes: could you try to choose `EAN-13` and add a single `0` in front of your code? If that works and the generated code look the same as the one you have, we could simplify entering those. But to my understanding, the barcode should be the same.
* For PDF417 we currently require JRuby. Should probably be doable in the docker container. I'll add it to my todo list.

> Would there be a way to support these kinds of barcodes, or have pictures of barcodes that aren't supported so I'd be able to add all my cards?

Pictures came up before, mainly to still have a reference of how the loyalty card looks like (or more information on it). But I like the idea of having a picture fallback for unsupported barcodes.

**Comment by Yhprum** [comment]
> could you try to choose `EAN-13` and add a single `0` in front of your code?

The barcode looks correct with the leading 0, cool - so we could add the UPC 12 format that just uses the EAN-13 format to generate it (and remove the leading 0 when saving the code)

Thanks!
